* Projects for Workshop 3
  
** Create a basic HTML form Calculator
Using two input boxes (for numbers) and several radio buttons (for the arithmetic operators such as +, -, *, etc), create a basic calculator using an HTML form and PHP code. The "submit" action of the form will have to take the user to a separate .php page that displays the results.

** Create a quiz with HTML forms and PHP
Choose a "victim" to be the recipient of a quiz that you will make. They will also make a quiz for you to answer. Using your knowledge of HTML, web forms and PHP, make a quiz with one page per question. At the end of the quiz, add up the number of correct answers the user has selected. Think about how you can incorporate:

- Multiple-choice questions
- Questions where the user types in some text (think about how you can be flexible about accepting multiple spellings, etc)
- Multimedia (images, videos, etc)

The quiz can be on any subject you like. One example could be a "Which X are you?"-style quiz (where X is "Game of Thrones character", etc). Try to make the quiz as inventive and fun as you can, but don't make the questions *too* hard!

** Create a product ordering form
   
Make a form for ordering custom builds of products, such as:

- computers
- cars
- clothing
- weddings
  
The user must select options from form components such as dropdown boxes or radio buttons, and their value must be added up to give a final price. For example, using /computers/ as our theme, the options could be:

#+BEGIN_SRC
Select a processor:
(processor drop down box)

Select the amount of RAM:
(radio buttons)

Which GPU?
(dropdown)

Any accessories?
(etc)
#+END_SRC

The selections are then added up to give a total price for the computer being ordered.

** Create a spreadsheet
Note: this one's a *real* challenge!   

See if you can create a basic spreadsheet using rows and column of text boxes. Have it so that if you enter a formula, the result is calculated on the next page when you click "submit" (along with the rest of the existing cells of the spreadsheet). The format for the formula could be something like:

#+BEGIN_SRC
= A1 + B4
= C8 - D2
= A4 * F3
#+END_SRC

You can check if a cell contains a number or formula by looking for the "=" sign.

See if you can also support operations over ranges of cells, such as:

#+BEGIN_SRC
= SUM F2:F7
#+END_SRC

...to sum all entries from column F, row 2 to column F row 7. You may find it useful to use regular expressions for this part of the exercise.

