* Projects for Workshop 3
  
** Create a basic HTML form Calculator
Using two input boxes (for numbers) and several radio buttons (for the arithmetic operators such as +, -, *, etc), create a basic calculator using an HTML form and PHP code. The "submit" action of the form will have to take the user to a separate .php page that displays the results.

** Create a quiz with HTML forms and PHP
Choose a "victim" to be the recipient of a quiz that you will make. They will also make a quiz for you to answer. Using your knowledge of HTML, web forms and PHP, make a quiz with one page per question. At the end of the quiz, add up the number of correct answers the user has selected. Think about how you can incorporate:

- Multiple-choice questions
- Questions where the user types in some text (think about how you can be flexible about accepting multiple spellings, etc)
- Multimedia (images, videos, etc)

Try to make the quiz as inventive and fun as you can, but don't make the questions *too* hard!

** Create a product ordering form
   
Make a form for ordering custom builds of products, such as:

- computers
- cars
- clothing
- weddings
  
The user must select options from form components such as dropdown boxes or radio buttons, and their value must be added up to give a final price. For example, using /computers/ as our theme, the options could be:

#+BEGIN_SRC
Select a processor:
(processor drop down box)

Select the amount of RAM:
(radio buttons)

Which GPU?
(dropdown)

Any accessories?
(etc)
#+END_SRC

The selections are then added up to give a total price for the computer being ordered.
