* Exercises for Workshop 2
** Exercise 10

Write an array variable of weather conditions with the following values: rain, sunshine, clouds, hail, sleet, snow, wind. Using the array variable for all the weather conditions, echo the following statement to the browser:

#+BEGIN_SRC php
"We've seen all kinds of weather this month. At the beginning of the month, we had snow and wind. Then came sunshine with a few clouds and some rain. At least we didn't get any hail or sleet."
#+END_SRC

Don't forget to include a title for your page, both in the header and on the page itself.

** Exercise 11

For this exercise, you will use a list of ten of the largest cities in the world. (Please note, these are not the ten largest, just a selection of ten from the largest cities.) Create an array with the following values: Tokyo, Mexico City, New York City, Mumbai, Seoul, Shanghai, Lagos, Buenos Aires, Cairo, London.

Print these values to the browser separated by commas, using a loop to iterate over the array. Sort the array, then print the values to the browser in an unordered list, again using a loop.

Add the following cities to the array: Los Angeles, Calcutta, Osaka, Beijing. Sort the array again, and print it once more to the browser in an unordered list.

** Exercise 12
You will again use the list of cities in Arrays Exercise 10. Here's the list, this time including countries as well as cities:

Tokyo, Japan; Mexico City, Mexico; New York City, USA; Mumbai, India; Seoul, Korea; Shanghai, China; Lagos, Nigeria; Buenos Aires, Argentina; Cairo, Egypt; London, England.

This time, create an associative array, using the countries as keys, the cities as values.

Create an array of country names. Loop through the array, using the names as keys to get the values from the associative array. Do this to print the following:

#+BEGIN_SRC php
"Tokyo is in Japan"
"Mexico City is in Mexico"
"New York City is in USA"
#+END_SRC

...etc

** Exercise 13

Create a function called "hello" that outputs that phrase we all know and love, "Hello, World!" to the browser. Call the function.

** Exercise 14
This PHP exercise has two parts. For the first, you will create a function to accept two arguments, perform a calculation using them, then return a sentence with the result to the browser.

The function will calculate the area of a rectangle, with the two arguments being width and height. (Reminder: area = width * height.) The sentence to be returned is "A rectangle of length $l and width $w has an area of $area.", where $l and $w are the arguments and $area is the result.

